name: SparkyLibX
version: 1.0.0
main: com.sparky.libx.SparkyLibX
api-version: 1.20
author: Андрій Будильников
description: Advanced mathematical and geometric library for Minecraft plugins
website: https://github.com/sparky/SparkyLibX